version: "3.8"
services:

  generator:
    image: knapset-generator
    pull_policy: always
    container_name: generator
    ports:
      - "8080:8080"
    read_only: true
    cap_drop:
      - 'ALL'

  naive-solver:
    image: naive-solver
    pull_policy: always
    container_name: naive-solver
    ports:
      - "8081:8081"
    read_only: false
    cap_drop:
      - 'ALL'

