name: Generator CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        working-directory: "knapset-generator"
        run: go build -v ./...

  run-tests-with-cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        working-directory: "knapset-generator"
        run: go build -v ./...

      - name: Run Tests
        working-directory: "knapset-generator"
        run: go test -v -cover ./...

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests-with-cover
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build ./knapset-generator --tag ghcr.io/peres-richard/knapsack-microservices-aws/knapset-generator:dev

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GHCR
        run: docker push ghcr.io/peres-richard/knapsack-microservices-aws/knapset-generator:dev

