name: Naive Solver

on:
  push:
    branches: [ main ]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: Install Pytest
        working-directory: naive_solver
        run: pip install -U pytest

      - name: Run Tests
        working-directory: naive_solver
        run: python3 -m pytest tests

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build ./naive_solver --tag ghcr.io/peres-richard/knapsack-microservices-aws/naive-solver:dev

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GHCR
        run: docker push ghcr.io/peres-richard/knapsack-microservices-aws/naive-solver:dev
